<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('invoices', function (Blueprint $table) {
            // Remove the global unique constraint
            // The default name generated by Laravel is 'invoices_invoice_number_unique'
            $table->dropUnique('invoices_invoice_number_unique');

            // Add a composite unique index for team_id and invoice_number
            $table->unique(['team_id', 'invoice_number'], 'invoices_team_invoice_number_unique');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('invoices', function (Blueprint $table) {
            $table->dropUnique('invoices_team_invoice_number_unique');
            $table->unique('invoice_number');
        });
    }
};
